# netlify.toml  – vypneme UI‑plugin jednou provždy

[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package  = "@netlify/plugin-nextjs"
enabled  = false   # <‑‑ tohle plugin definitivně vypne
