# netlify.toml  – vypne UI‑plugin @netlify/plugin-nextjs

[build]
command  = "npm run build"
publish  = ".next"

[[plugins]]
package  = "@netlify/plugin-nextjs"
enabled  = false            # <‑‑ tím plugin z UI násilně vypneme
